# No default os and language here, due to special macos config

jobs:
  include:
    - name: Python 3.7 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.7'
    - name: Python 3.8 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.8'
    # See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # for macos config peculiarities.
    - name: Python 3.7 on MacOS X (xcode 10.3)
      os: osx
      language: shell
      osx_image: xcode10.3
      python: '3.7'
    - name: Python 3.8 on MacOS X (xcode 11.3)
      os: osx
      language: shell
      osx_image: xcode11.3
      python: '3.8'

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

before_install:
  - bash build_tools/install-conda.sh
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="${MINICONDA_DIR}/bin:$PATH"
  - conda activate test
  - hash -r
  - bash build_tools/install-requirements.sh

install:
  - pip install -e .

before_script:
  - which deepnog
  - flake8 --exit-zero .

script:
  - pytest deepnog/utils/tests/test_imports.py --hide-torch --cov
  - pytest --cov=deepnog --cov-append

after_success:
  - codecov

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"
      - "$HOME/deepnog_data"

branches:
  only:
  - master
  - develop
